#!/bin/sh

if ! git diff-index --quiet HEAD --; then
  echo 'Uncommitted local changes detected. Stashing...'
  git stash
fi

echo 'Syncing Master with Remote...'
{
  git checkout master
  git pull origin master
} > /dev/null

echo 'Creating New Branch...'
git checkout -b "${1}"